name: namae-api
on:
  push:
    paths:
      - api/*
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node
      - uses: actions/checkout
      - run: cd api
      - run: yarn install