name: test
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@master
      - uses: actions/checkout@master
      - name: Install dependencies
        run: yarn install
      - name: Test
        run: yarn test
      - name: Upload coverage
        run: |
          cat ./coverage/lcov.info | yarn codacy-coverage
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
